# Generated by Django 2.2.7 on 2020-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Mname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('Gender', models.CharField(max_length=5)),
                ('phone_no', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=100)),
                ('R_o_v', models.CharField(max_length=100)),
            ],
        ),
    ]
